#!/bin/bash

###     Title:          Archive and backup script
###     Date:           16 July 2022
###     Author:         CJ Glawson
###     Version:        1.0.1

# Setting Variables
# Path of folder to backup
backup_files="/home/"

# Path of Destination Folder/Path of the backup
dest="/tmp"

# **********************
# Setting our Start Time
# **********************
now=$(date +"%H:%M:%S")

# Setting values for our filename/archive file
currentDate=$(date +"%y-%m-%d")
hostname=$(hostname -s)
archive_file="$hostname-$currentDate.tgz"

# ******************************************************
# Let the user know that backup is starting/running...
# ******************************************************

# Clear Display
clear;

echo "Backup up $backup_files to $archive_file"
echo "Process is starting"

# ********************
# Print the Start Time
# ********************
echo SCript start time: "$now"

# ******************************
# Backup the files using Tar Gz
# ******************************
# >> you need to download pv command for this to work ->- apt install pv
# original tar command from exercise
# tar -czPf $dest/$archive_file $backupfiles
#           ## piped to pv command to show progress - shows progress animation ##
tar -czPf - $backup_files   | (pv -p --timer --rate --bytes > $dest/$archive_file )


# *****************************
# Print the end status message
# *****************************
echo "Backup finished!";
# ********************************
# Need to set end time to now var
# ********************************
now=$(date +"%H:%M:%S")

echo Script end time: "$now"
